"""
HTTP scaffold template for an external system under test (SUT).

Generated by gavel scaffold — see docs/specs/schema-external-runner.md for
the full request/response schema reference.

Quick-start
-----------
1. Implement ``handle()`` below.
2. Expose ``system.handle_http_request(body_dict)`` from your HTTP handler.
3. Return the dict to the caller as JSON with Content-Type: application/json.

Request schema  : ExternalTaskRequest  (gavel_ai.models.runtime)
Response schema : ExternalResponseEnvelope (gavel_ai.models.runtime)
Schema docs     : docs/specs/schema-external-runner.md
"""

from typing import Any, Dict

from gavel_ai.models.runtime import ExternalTaskRequest
from gavel_ai.scaffolds import RemoteSystemUnderTest


class MyHTTPSystemUnderTest(RemoteSystemUnderTest):
    """Minimal HTTP SUT scaffold.  Replace the body of ``handle`` with your logic."""

    def handle(self, request: ExternalTaskRequest) -> Dict[str, Any]:
        """
        Process a Gavel task request and return a result dict.

        Args:
            request: Validated ExternalTaskRequest with:
                - scenario_id    : str      — identifies the scenario
                - scenario_input : str|dict — raw scenario input
                - rendered_prompt: str      — ready-to-send prompt (max 32 KB)
                - custom_config  : dict     — pass-through SUT config
                - trace_id       : str|None — telemetry correlation
                - metadata       : dict     — extra per-invocation data

        Returns:
            A dict whose fields will populate the ``result`` key of the response
            envelope.  Example: {"output": "my response text"}

        Raises:
            Any exception here is caught and surfaced as status="error".
        """
        # TODO: replace with your real SUT call
        output = f"SUT response for scenario {request.scenario_id}"
        return {"output": output}


# ── Entry-point (optional — adapt to your HTTP framework) ──────────────────
if __name__ == "__main__":
    import json
    import sys

    # Example: read a raw JSON request from stdin and print the response to stdout.
    raw: Dict[str, Any] = json.load(sys.stdin)
    system = MyHTTPSystemUnderTest()
    response = system.handle_http_request(raw)
    print(json.dumps(response, indent=2))
