"""
Script scaffold template for an external system under test (SUT).

Generated by gavel scaffold — see docs/specs/schema-external-runner.md for
the full request/response schema reference.

How it works
------------
Gavel writes ``request.json`` to a temp directory, then launches this script
with that directory as the working directory.  After the script exits 0, Gavel
reads ``response.json`` from the same directory.

Quick-start
-----------
1. Implement ``handle()`` below.
2. Run with: ``python script_scaffold.py`` (from the temp directory), OR set
   your eval config's ``command`` to ``["python", "/path/to/script_scaffold.py"]``.

Request file  : request.json  (ExternalTaskRequest schema)
Response file : response.json (ExternalResponseEnvelope schema)
Schema docs   : docs/specs/schema-external-runner.md
"""

from typing import Any, Dict

from gavel_ai.models.runtime import ExternalTaskRequest
from gavel_ai.scaffolds import ScriptSystemUnderTest


class MyScriptSystemUnderTest(ScriptSystemUnderTest):
    """Minimal script SUT scaffold.  Replace the body of ``handle`` with your logic."""

    def handle(self, request: ExternalTaskRequest) -> Dict[str, Any]:
        """
        Process a Gavel task request and return a result dict.

        Args:
            request: Validated ExternalTaskRequest with:
                - scenario_id    : str      — identifies the scenario
                - scenario_input : str|dict — raw scenario input
                - rendered_prompt: str      — ready-to-send prompt (max 32 KB)
                - custom_config  : dict     — pass-through SUT config
                - trace_id       : str|None — telemetry correlation
                - metadata       : dict     — extra per-invocation data

        Returns:
            A dict whose fields will populate the ``result`` key of the response
            envelope.  Example: {"output": "my response text"}

        Raises:
            Any exception here is caught and surfaced as status="error".
        """
        # TODO: replace with your real SUT call
        output = f"SUT response for scenario {request.scenario_id}"
        return {"output": output}


# ── Script entry-point ─────────────────────────────────────────────────────
if __name__ == "__main__":
    MyScriptSystemUnderTest().main()
