#!/usr/bin/env python3
"""
Regenerate references/cli-reference.md from live gavel CLI --help output.
Run this script whenever a CLI command is added or changed:

    python scripts/update_cli_reference.py

Writes to: <skill-dir>/references/cli-reference.md
"""
import subprocess
from pathlib import Path

SKILL_DIR = Path(__file__).parent.parent
REFERENCES_DIR = SKILL_DIR / "references"
OUTPUT_FILE = REFERENCES_DIR / "cli-reference.md"

SUBCOMMANDS: list[list[str]] = [
    [],
    ["oneshot"],
    ["oneshot", "create"],
    ["oneshot", "run"],
    ["oneshot", "judge"],
    ["oneshot", "report"],
    ["oneshot", "list"],
    ["oneshot", "milestone"],
    ["conv"],
    ["conv", "create"],
    ["conv", "generate"],
    ["autotune"],
    ["autotune", "create"],
    ["autotune", "run"],
]


def run_help(args: list[str]) -> str:
    result = subprocess.run(
        ["gavel"] + args + ["--help"],
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


EXTERNAL_RUNNER_NOTE: str = """
## External test subject execution (`test_subject_type: "external"`)

The `external`/`http`|`script` execution path (introduced by the external-runner
initiative) does **not** add new CLI flags to `gavel oneshot run`, `judge`, or
`report`. All existing commands work unchanged for external evals:

```bash
# Run an external eval exactly as you would a local eval:
gavel oneshot run --eval <name>

# Judge and report work identically:
gavel oneshot judge --run <run-id>
gavel oneshot report --run <run-id>
```

The difference is entirely in `eval_config.json` — setting `test_subject_type:
"external"`, `protocol: "http"|"script"`, and the protocol-specific `config`
block. See `references/config-schema.md` for the full field reference.

**CLI output for external runs**

External runs produce the same CLI output as local runs, with additional
per-invocation log entries in `run.log`. Each entry names the protocol
(`http`/`script`), the target (endpoint URL or script command), the outcome tier
(`process_failure` or `process_success_with_issue`), and the invocation's
`trace_id`. On a halting failure, the Rich panel printed to stderr names the
tier, the cause, the `trace_id`, and the path to `run.log` — consistent with
the existing error-display convention (human-readable cause + log pointer, never
a raw stack trace).

**`gavel oneshot create --type`**

The `--type` flag currently documents `local` and `in-situ`. `in-situ` is a
deprecated alias for `external` — configs using `test_subject_type: "in-situ"`
are accepted but emit a deprecation warning; update to `"external"`.
"""


def build_reference() -> str:
    lines: list[str] = [
        "# Gavel CLI Reference",
        "",
        "> Auto-generated by `scripts/update_cli_reference.py`. Do not edit manually.",
        "> Re-run the script after any CLI change.",
        "",
    ]

    for args in SUBCOMMANDS:
        cmd = "gavel " + " ".join(args) if args else "gavel"
        output = run_help(args)
        lines.append(f"## `{cmd}`")
        lines.append("")
        lines.append("```")
        lines.append(output)
        lines.append("```")
        lines.append("")

    lines.append(EXTERNAL_RUNNER_NOTE.strip())
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    REFERENCES_DIR.mkdir(parents=True, exist_ok=True)
    content = build_reference()
    OUTPUT_FILE.write_text(content, encoding="utf-8")
    print(f"Written: {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
