# Copyright 2026 Cicadas Contributors
# SPDX-License-Identifier: Apache-2.0

import argparse
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

from tokens import append_entry
from utils import (
    WorktreeDirtyError,
    create_worktree,
    emit,
    get_default_branch,
    load_config,
    get_project_root,
    get_registry_dir,
    load_json,
    parse_partitions_dag,
    save_json,
    worktree_path,
    worktree_policy,
)


def _write_context_md(worktree_dir: Path, cicadas: Path, modules: list[str], initiative: str | None) -> None:
    """Assemble context.md into the worktree root for agent bootstrapping."""
    lines = ["# Worktree Context\n", "> Auto-generated by branch.py. Do not commit — see .gitignore.\n\n"]

    # Canon summary
    canon_summary = cicadas / "canon" / "summary.md"
    if canon_summary.exists():
        lines.append("## Canon Summary\n\n")
        lines.append(canon_summary.read_text())
        lines.append("\n\n")

    repo_context = cicadas / "canon" / "repo-context.md"
    if repo_context.exists():
        lines.append("## Repo Context\n\n")
        lines.append(repo_context.read_text())
        lines.append("\n\n")

    # Module snapshots
    module_snapshots = cicadas / "canon" / "modules"
    if module_snapshots.exists() and modules:
        snap_lines = []
        for mod in modules:
            snap = module_snapshots / f"{mod.replace('/', '-')}.md"
            if snap.exists():
                snap_lines.append(f"## Module: {mod}\n\n{snap.read_text()}\n\n")
        if snap_lines:
            lines.append("## Module Snapshots\n\n")
            lines.extend(snap_lines)

    # Approach and tasks from active initiative
    if initiative:
        active = cicadas / "active" / initiative
        for spec in ["approach.md", "tasks.md"]:
            spec_path = active / spec
            if spec_path.exists():
                lines.append(f"## {spec}\n\n{spec_path.read_text()}\n\n")

    context_path = worktree_dir / "context.md"
    context_path.write_text("".join(lines))


def _resolve_parent_ref(root: Path, parent: str | None) -> str | None:
    """Resolve a parent branch name to a usable local or remote git ref."""
    if not parent:
        return None

    candidates = [
        parent,
        f"refs/heads/{parent}",
        f"origin/{parent}",
        f"refs/remotes/origin/{parent}",
    ]
    for candidate in candidates:
        try:
            subprocess.run(["git", "rev-parse", "--verify", candidate], cwd=root, check=True, capture_output=True)
            return candidate
        except subprocess.CalledProcessError:
            continue
    return parent


def create_branch(name, intent, modules, initiative=None, from_branch=None, owner="unknown", worktree_dir_override=None, no_worktree=False, force_worktree=False):
    root = get_project_root()
    cicadas = root / ".cicadas"
    registry = load_json(get_registry_dir() / "registry.json")
    default_branch = get_default_branch()
    policy = worktree_policy(load_config())

    if name in registry.get("branches", {}):
        print(f"[ERR]  Branch {name} already registered.")
        return

    # Check for module overlaps
    my_mods = {m.strip() for m in modules.split(",") if m.strip()}
    conflicts = []
    for b_name, b_info in registry.get("branches", {}).items():
        overlap = my_mods.intersection(set(b_info.get("modules", [])))
        if overlap:
            conflicts.append(f"{b_name} (Overlaps: {', '.join(overlap)})")

    # Determine parent branch
    if from_branch:
        parent = from_branch
    elif name.startswith("fix/") or name.startswith("tweak/") or name.startswith("skill/"):
        parent = default_branch
    elif initiative:
        parent = f"initiative/{initiative}"
    else:
        parent = None
    parent_ref = _resolve_parent_ref(root, parent)

    # --- Worktree logic: decide path before creating git branch ---
    use_worktree = False
    worktree_target = None
    wt_path_str = None
    if force_worktree:
        use_worktree = True
        worktree_target = Path(worktree_dir_override) if worktree_dir_override else worktree_path(root, name)
    elif not no_worktree:
        is_lightweight = name.startswith(("fix/", "tweak/", "skill/"))
        if is_lightweight:
            if policy["lightweight"]:
                use_worktree = True
                worktree_target = Path(worktree_dir_override) if worktree_dir_override else worktree_path(root, name)
        elif initiative:
            approach_path = cicadas / "active" / initiative / "approach.md"
            partitions = parse_partitions_dag(approach_path)
            partition = next((p for p in partitions if p["name"] == name), None)

            if partition is None and partitions:
                print(f"[WARN] Partition '{name}' not found in approach.md partitions block — treating as sequential")
            elif partition and partition.get("depends_on") == [] and policy["parallel_features"]:
                use_worktree = True
                worktree_target = Path(worktree_dir_override) if worktree_dir_override else worktree_path(root, name)

    if use_worktree:
        # For parallel partitions: create branch WITHOUT switching (stay on parent)
        # so we can immediately add a worktree pointing at it.
        branch_cmd = ["git", "branch", name]
        if parent_ref:
            branch_cmd.append(parent_ref)
        subprocess.run(branch_cmd, check=True, cwd=root)
        try:
            subprocess.run(["git", "push", "-u", "origin", name], check=True, cwd=root)
            print(f"[INFO] Pushed {name} to remote.")
        except subprocess.CalledProcessError:
            print(f"[WARN] Could not push {name} to remote. Push manually: git push -u origin {name}")
        # Create worktree
        try:
            created = create_worktree(root, name, worktree_target)
            wt_path_str = str(created)
            print(f"[OK]   Worktree created: {created}")
            emit(initiative or name, "worktree.created", {"branch": name, "worktree_path": wt_path_str})
            _write_context_md(created, cicadas, list(my_mods), initiative)
            print(f"[INFO] context.md written to worktree root (canon summary + module snapshots + tasks)")
            print(f"[INFO] Open this worktree in your editor or agent: {created}")
        except subprocess.CalledProcessError as e:
            print(f"[ERR]  git worktree add failed: {e}")
            sys.exit(1)
    else:
        # Sequential (or unregistered) partition: standard checkout -b
        checkout_cmd = ["git", "checkout", "-b", name]
        if parent_ref:
            checkout_cmd.append(parent_ref)
        subprocess.run(checkout_cmd, check=True, cwd=root)
        try:
            subprocess.run(["git", "push", "-u", "origin", name], check=True, cwd=root)
            print(f"[INFO] Pushed {name} to remote.")
        except subprocess.CalledProcessError:
            print(f"[WARN] Could not push {name} to remote. Push manually: git push -u origin {name}")
        _write_context_md(root, cicadas, list(my_mods), initiative)
        print(f"[INFO] context.md written to project root (canon summary + module snapshots + tasks)")

    # Register
    branch_info = {
        "intent": intent,
        "modules": list(my_mods),
        "owner": owner,
        "created_at": datetime.now(UTC).isoformat(),
    }
    if wt_path_str:
        branch_info["worktree_path"] = wt_path_str
    if initiative:
        if initiative not in registry.get("initiatives", {}):
            print(f"[WARN] Initiative {initiative} not found.")
        else:
            branch_info["initiative"] = initiative

    registry.setdefault("branches", {})[name] = branch_info
    save_json(get_registry_dir() / "registry.json", registry)
    emit(initiative or name, "branch.created", {"branch": name, "intent": intent, "modules": list(my_mods)})

    # Active dir is keyed by initiative name, not branch name.
    if initiative:
        active_name = initiative
    elif "/" in name:
        active_name = name.split("/", 1)[1]
    else:
        active_name = name
    (cicadas / "active" / active_name).mkdir(parents=True, exist_ok=True)

    # Write implementation/branch-start token boundary entry
    append_entry(cicadas / "active" / active_name / "tokens.json", initiative=active_name, phase="implementation", subphase=name, source="unavailable")

    print(f"[OK]   Branch registered: {name}")
    if conflicts:
        print(f"[WARN] Module overlaps detected: {'; '.join(conflicts)}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Register a feature branch with conflict detection")
    parser.add_argument("name")
    parser.add_argument("--intent", required=True)
    parser.add_argument("--modules", default="")
    parser.add_argument("--initiative", help="Link to an active initiative")
    parser.add_argument("--from", dest="from_branch", help="Parent branch to fork from (defaults to initiative branch)")
    parser.add_argument("--worktree-dir", dest="worktree_dir", help="Override default worktree directory path")
    parser.add_argument("--worktree", action="store_true", help="Force a linked worktree even if the default policy would use the current workspace")
    parser.add_argument("--no-worktree", action="store_true", help="Force plain branch even if depends_on is empty")
    args = parser.parse_args()
    create_branch(
        args.name,
        args.intent,
        args.modules,
        initiative=args.initiative,
        from_branch=args.from_branch,
        worktree_dir_override=args.worktree_dir,
        no_worktree=args.no_worktree,
        force_worktree=args.worktree,
    )
